### ISSUE TITLE
Feature design

### ISSUE THREAD

**Issue by junhwi** [junhwi/msg#1]
@pinetree408 Let's discuss in Korean.

지금은 아래와 같은 `models.yml`파일을 자동으로 생성해서
training 시킬때마다 어떤 configuration으로 구현체의 어떤 commit으로 생성한 모델인지 track해 줍니다.
```yaml
models:
  v1:
    commit: bb134104798af50d825dd9bc274c74cad6601d49
    desc: ''
    settings: {DISCOUNT: 0.99, INPUT_RANGE: 128, MAX_EPISODE: 5000, MAX_TRIAL: 500,
      NUM_ACTION: 6, OBSERVE: 100, SCREEN_HEIGHT: 4, SCREEN_WIDTH: 1, TARGET_UPDATE_INTERVAL: 1000,
      TRAIN_INTERVAL: 4}
  v2:
    commit: f72533ff1e3a8dfc37ae6f91c9bd6ec6f1b5909d
    desc: vector + chage of fitness
    settings: {DISCOUNT: 0.99, INPUT_RANGE: 128, MAX_EPISODE: 10000, MAX_TRIAL: 500,
      NUM_ACTION: 6, OBSERVE: 100, SCREEN_HEIGHT: 6, SCREEN_WIDTH: 1, TARGET_UPDATE_INTERVAL: 1000,
      TRAIN_INTERVAL: 4}
pk: 10
```

# Example usage
```py
import msg

version = msg.check_in('YAML_DB_FILE_PATH', 'DESCRIPTION', CONFIG_DICT)
```

# Features
General purpose experiment framework으로 만들면 좋을 것 같은 생각입니다.
1. Training후 생성된 model의 설정 및 version tracking
2. 해당 version의 model을 불러와서 test를 반복적으로 수행할 수 있는 task runner
3. Notification?

p.s. Private repo? Public repo?

어떤 기능부터 시작해보면 좋을 까요?
